"""Repository-level checks: provenance, licences, and generated files.

These are about the repo as a whole rather than any one file, so they run once
against the root instead of per file.
"""
from __future__ import annotations

import pathlib
import re
import subprocess

from ..context import Context

GENERATED = re.compile(r"GENERATED from|GENERATED by|— GENERATED", re.I)
DO_NOT_EDIT = re.compile(r"do not edit", re.I)


def run(ctx: Context) -> None:
    if ctx.root.is_file():
        _generated_files(ctx)
        return
    _source_md(ctx)
    _licenses(ctx)
    _generated_files(ctx)


def _source_md(ctx: Context) -> None:
    """UMB-DAT-001 — every dataset directory carries its provenance."""
    raw = ctx.root / "data" / "raw"
    if not raw.is_dir():
        return
    for d in sorted(raw.iterdir()):
        if not d.is_dir():
            continue
        if not (d / "SOURCE.md").exists():
            ctx.report("source-md-present", d, 1,
                       f"data/raw/{d.name}/ has no SOURCE.md",
                       "origin URL, accessor, download date, licence, known caveats")
    # loose files directly under data/raw/ still need provenance for the directory
    loose = [f for f in raw.iterdir() if f.is_file() and f.suffix in (".csv", ".json", ".parquet")]
    if loose and not (raw / "SOURCE.md").exists():
        ctx.report("source-md-present", raw, 1,
                   f"data/raw/ holds {len(loose)} data file(s) and no SOURCE.md", "")


def _licenses(ctx: Context) -> None:
    """UMB-DAT-004 — code MIT, data and content CC BY 4.0, both stated."""
    names = {p.name for p in ctx.root.iterdir()} if ctx.root.is_dir() else set()
    has_split = {"LICENSE-CODE", "LICENSE-CONTENT"} <= names
    has_single = bool({"LICENSE", "LICENSE.md", "LICENSE.txt"} & names)
    if not has_split:
        if has_single:
            ctx.report("license-present", ctx.root, 1,
                       "one LICENSE file — code and content are licensed differently",
                       "LICENSE-CODE (MIT) and LICENSE-CONTENT (CC BY 4.0)")
        else:
            ctx.report("license-present", ctx.root, 1, "no licence file",
                       "LICENSE-CODE (MIT) and LICENSE-CONTENT (CC BY 4.0)")


def _generated_files(ctx: Context) -> None:
    """UMB-PRO-001 — generated files are never hand-edited.

    Detected against git: a file that declares itself generated and has
    uncommitted changes was edited by hand, not rebuilt.
    """
    root = ctx.root if ctx.root.is_dir() else ctx.root.parent
    try:
        res = subprocess.run(
            ["git", "-C", str(root), "status", "--porcelain", "--untracked-files=no"],
            capture_output=True, text=True, timeout=15)
    except (OSError, subprocess.SubprocessError):
        return
    if res.returncode != 0:
        return

    try:
        top = subprocess.run(["git", "-C", str(root), "rev-parse", "--show-toplevel"],
                             capture_output=True, text=True, timeout=15).stdout.strip()
    except (OSError, subprocess.SubprocessError):
        return
    if not top:
        return
    base = pathlib.Path(top)

    for line in res.stdout.splitlines():
        if len(line) < 4:
            continue
        path = base / line[3:].strip().strip('"')
        if not path.is_file() or path.suffix in (".png", ".pdf", ".woff2"):
            continue
        # only report what the caller asked us to look at
        if ctx.root.is_file():
            if path.resolve() != ctx.root.resolve():
                continue
        elif not path.resolve().is_relative_to(ctx.root.resolve()):
            continue
        try:
            head = path.read_text(errors="replace")[:600]
        except OSError:
            continue
        if GENERATED.search(head) and DO_NOT_EDIT.search(head):
            ctx.report("generated-file-edited", path, 1,
                       "generated file has uncommitted hand edits",
                       "change the source in tokens/src/ or rules/rules.yaml and rebuild")


def register() -> dict:
    return {"repo": run}
